project/api/urls.py
from django.conf.urls import url

from . import views
from contests.globalviews import ContestsApiView

app_name = 'api'

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view()),
    url(r'^fs/(?P<filename>new)$', views.NewFileView.as_view()),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/cancel$', views.JobCancelView.as_view()),
    url(r'^compiler-settings$', views.CompilerSettingsView.as_view()),
    url(r'^plagiarism/take$', views.PlagiarismTakeView.as_view()),
    url(r'^plagiarism/put$', views.PlagiarismPutView.as_view()),
    url(r'^sleep$', views.SleepView.as_view()),
    url(r'^printing$', views.PrintingView.as_view()),
    url(r'^printing/(?P<printout_id>\d+)$', views.PrintingDoneView.as_view()),
    url(r'^auth/check$', views.AuthCheckView.as_view()),
    url(r'^contests$', ContestsApiView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/courses/urls.py
from django.conf.urls import url, include
from django.urls import path

from courses.settings.urls import settings_urlpatterns
from . import views, globalviews, assignviews, problemviews, quizviews, queueviews

app_name = 'courses'

quiz_urlpatterns = ([
    url(r'^$', quizviews.CourseQuizzesView.as_view(), name='list'),
    url(r'^sessions/(?P<session_id>[0-9]+)/$', quizviews.CourseQuizzesSessionView.as_view(), name='session'),
    url(r'^sessions/(?P<session_id>[0-9]+)/answers/$', quizviews.CourseQuizzesAnswersView.as_view(), name='answers'),
    url(r'^sessions/(?P<session_id>[0-9]+)/answers/api/$', quizviews.CourseQuizzesSaveMarkView.as_view(), name='save_mark'),
    url(r'^sessions/(?P<session_id>[0-9]+)/finish/$', quizviews.CourseQuizzesFinishView.as_view(), name='finish'),
    url(r'^sessions/(?P<session_id>[0-9]+)/save-answer/$', quizviews.SaveAnswerAPIView.as_view(), name='save_answer'),
    url(r'^sessions/(?P<session_id>[0-9]+)/delete/$', quizviews.CourseQuizzesDeleteSessionView.as_view(),
        name='delete_session'),
    url(r'^sessions/(?P<session_id>[0-9]+)/submit-comment/$', quizviews.CourseQuizzesSubmitCommentView.as_view(),
        name='submit_comment'),
    url(r'^start/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesStartView.as_view(), name='start'),
    url(r'^rating/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesRatingView.as_view(), name='rating'),
    url(r'^sheet/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesSheetView.as_view(), name='sheet'),
    url(r'^turn-on/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesTurnOnView.as_view(), name='turn_on'),
    url(r'^turn-off/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesTurnOffView.as_view(), name='turn_off'),
], 'quizzes')

queue_urlpatterns = ([
    url(r'^$', queueviews.ListView.as_view(), name='list'),
    url(r'^(?P<queue_id>[0-9]+)/add/$', queueviews.AddView.as_view(), name='add'),
    url(r'^(?P<queue_id>[0-9]+)/join/$', queueviews.JoinView.as_view(), name='join'),
    url(r'^(?P<queue_id>[0-9]+)/items/(?P<item_id>[0-9]+)/start/$', queueviews.StartView.as_view(), name='start'),
    url(r'^(?P<queue_id>[0-9]+)/items/(?P<item_id>[0-9]+)/finish/$', queueviews.FinishView.as_view(), name='finish'),
], 'queues')

assignment_urlpatterns = ([
    url(r'^$', assignviews.CourseEmptyAssignView.as_view(), name='empty'),
    url(r'^(?P<user_id>[0-9]+)/$', assignviews.CourseAssignView.as_view(), name='index'),
    url(r'^(?P<user_id>[0-9]+)/new-penalty/$', assignviews.CourseAssignCreatePenaltyProblem.as_view(), name='new_penalty'),
    url(r'^(?P<user_id>[0-9]+)/delete-penalty/(?P<assignment_id>[0-9]+)/$',
        assignviews.CourseAssignDeletePenaltyProblem.as_view(), name='delete_penalty'),
    url(r'^(?P<user_id>[0-9]+)/api/problem/$',
        assignviews.CourseAssignProblemApiView.as_view(), name='api_problem'),
    url(r'^(?P<user_id>[0-9]+)/api/criterion/$',
        assignviews.CourseAssignCriterionApiView.as_view(), name='api_criterion'),
    url(r'^(?P<user_id>[0-9]+)/api/topic-problems/(?P<topic_id>[0-9]+)/$',
        assignviews.ListTopicProblemsApiView.as_view()),
], 'assignment')

problem_urlpatterns = [
    url(r'^problemset/$', problemviews.EmptyView.as_view(), name='course_problems'),
    url(r'^problemset/(?P<topic_id>[0-9]+)/$', problemviews.FullTopicListView.as_view(), name='course_problems_topic'),
    url(r'^problemset/(?P<topic_id>[0-9]+)/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', problemviews.TopicItemView.as_view(), name='course_problems_topic_problem'),
    url(r'^problemset/(?P<topic_id>[0-9]+)/common/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', problemviews.TopicCommonProblemsItemView.as_view(), name='course_problems_topic_common_problem'),
    url(r'^problemset/common/$', problemviews.CommonProblemsListView.as_view(), name='course_common_problems'),
    url(r'^problemset/common/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', problemviews.CommonProblemsItemView.as_view(), name='course_common_problems_problem'),
    url(r'^problems/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', problemviews.AnyProblemView.as_view(), name='course_problems_problem'),
]

single_course_urlpatterns = [
    url(r'^$', views.CourseInfoView.as_view(), name='show_course_info'),
    url(r'^standings/$', views.CourseStandingsView.as_view(), name='course_standings'),
    url(r'^standings/wide/$', views.CourseStandingsWideView.as_view(), name='course_standings_wide'),
    url(r'^sheet/$', views.CourseSheetView.as_view(), name='course_sheet'),
    url(r'^sheet/edit/$', views.CourseSheetEditView.as_view(), name='course_sheet_edit'),
    url(r'^sheet/edit/api/(?P<membership_id>[0-9]+)/(?P<activity_id>[0-9]+)/$',
        views.CourseSheetEditApiView.as_view(), name='course_sheet_edit_api'),
    url(r'^compilers/$', views.CourseCompilersView.as_view(), name='course_compilers'),

    url(r'^submit/$', views.CourseSubmit2View.as_view(), name='course_submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.CourseSubmissionView.as_view(), name='course_submission'),

    url(r'^solutions/$', views.CourseAllSolutionsView.as_view(), name='all_solutions'),
    url(r'^my/solutions/$', views.CourseMySolutionsView.as_view(), name='my_solutions'),

    url(r'^my/problems/$', views.CourseMyProblemsView.as_view(), name='my_problems'),

    url(r'^my/attempts/$', views.CourseMyAttemptsView.as_view(), name='my_attempts'),
    url(r'^blocked/$', views.CourseBlockedView.as_view(), name='blocked'),

    # Messages

    url(r'^mailbox/$', views.CourseMessagesEmptyView.as_view(), name='messages_empty'),
    url(r'^mailbox/(?P<thread_id>[0-9]+)/$', views.CourseMessagesView.as_view(), name='messages'),
    url(r'^mailbox/(?P<thread_id>[0-9]+)/delete/$', views.CourseMessagesThreadDeleteView.as_view(), name='messages_thread_delete'),
    url(r'^mailbox/(?P<thread_id>[0-9]+)/resolve/$', views.CourseMessagesThreadResolveView.as_view(), name='messages_thread_resolve'),
    url(r'^mailbox/(?P<thread_id>[0-9]+)/messages/(?P<message_id>[0-9]+)/attachment/(?P<filename>.*)$',
        views.CourseMessagesDownloadView.as_view(), name='messages_download'),
    url(r'^mailbox/new/$', views.CourseMessagesNewView.as_view(), name='messages_new'),

    url(r'^quizzes/', include(quiz_urlpatterns)),
    url(r'^queues/', include(queue_urlpatterns)),
    url(r'^settings/', include(settings_urlpatterns)),
    url(r'^assign/', include(assignment_urlpatterns)),

    path('', include(problem_urlpatterns)),
]

urlpatterns = [
    url(r'^$', globalviews.ActiveCourseListView.as_view(), name='index'),
    url(r'^all/$', globalviews.AllCourseListView.as_view(), name='index_all'),
    url(r'^my/$', globalviews.MyCourseListView.as_view(), name='my'),
    url(r'^new/$', globalviews.CourseCreateView.as_view(), name='new'),

    url(r'^criteria/$', views.CriterionListView.as_view(), name='criterion_index'),
    url(r'^criteria/new/$', views.CriterionCreateView.as_view(), name='criterion_new'),
    url(r'^criteria/(?P<pk>[0-9]+)/edit/$', views.CriterionUpdateView.as_view(), name='criterion_edit'),
    url(r'^criteria/(?P<pk>[0-9]+)/delete/$', views.CriterionDeleteView.as_view(), name='criterion_delete'),

    url(r'^(?P<course_id>[0-9]+)/', include(single_course_urlpatterns)),
]

project/problems/folders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<folder_id_or_root>[^/]+)/$', views.ShowFolderView.as_view(), name='show_folder'),
    url(r'^(?P<folder_id_or_root>[^/]+)/new/folder/$', views.CreateFolderView.as_view(), name='create_folder'),
    url(r'^(?P<folder_id_or_root>[^/]+)/new/problem/$', views.CreateProblemView.as_view(), name='create_problem'),
    url(r'^(?P<folder_id_or_root>[^/]+)/properties/$', views.UpdateFolderView.as_view(), name='folder_properties'),
    url(r'^(?P<folder_id_or_root>[^/]+)/access/$', views.FolderAccessView.as_view(), name='folder_access'),
    url(r'^(?P<folder_id_or_root>[^/]+)/delete/$', views.DeleteFolderView.as_view(), name='delete_folder'),
    url(r'^(?P<folder_id_or_root>[^/]+)/import-from-polygon/$', views.ImportFromPolygonView.as_view(), name='import_from_polygon'),
]

project/problems/problem/urls.py
from django.conf.urls import include, url
from django.urls import path

from problems.problem import views as pviews

problem_urlpatterns = [
    url(r'^$', pviews.ProblemOverviewView.as_view(), name='overview'),
    url(r'^statement/(?P<filename>.+)?$', pviews.ProblemStatementView.as_view(), name='statement'),
    url(r'^tutorial/(?P<filename>.+)?$', pviews.ProblemTutorialView.as_view(), name='tutorial'),

    url(r'^tests/$', pviews.ProblemTestsView.as_view(), name='tests'),
    url(r'^tests/browse/$', pviews.ProblemBrowseTestsView.as_view(), name='browse_tests'),
    url(r'^tests/reorder/$', pviews.ProblemReorderTestsView.as_view(), name='reorder_tests'),
    url(r'^tests/(?P<test_number>[0-9]+)/$', pviews.ProblemTestsTestView.as_view(), name='show_test'),
    url(r'^tests/upload/$', pviews.ProblemTestsUploadArchiveView.as_view(), name='upload_archive'),
    url(r'^tests/new/$', pviews.ProblemTestsNewView.as_view(), name='new_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/edit/$', pviews.ProblemTestsTestEditView.as_view(), name='edit_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/delete/$', pviews.ProblemTestsDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/image/(?P<filename>.+)$', pviews.ProblemTestsTestImageView.as_view(), name='test_image'),
    url(r'^tests/batch/set/time-limit/$', pviews.ProblemTestsSetTimeLimitView.as_view(), name='tests_mass_time_limit'),
    url(r'^tests/batch/set/memory-limit/$', pviews.ProblemTestsSetMemoryLimitView.as_view(), name='tests_mass_memory_limit'),
    url(r'^tests/batch/set/points/$', pviews.ProblemTestsSetPointsView.as_view(), name='tests_mass_points'),
    url(r'^tests/batch/delete/$', pviews.ProblemTestsBatchDeleteView.as_view(), name='tests_mass_delete'),
    url(r'^tests/batch/download/$', pviews.ProblemTestsDownloadArchiveView.as_view(), name='tests_batch_download'),

    url(r'^tests/open/input-(?P<test_number>[0-9]+)\.txt$', pviews.ProblemTestsTestDataView.as_view(kind='input', download=False), name='test_input_open'),
    url(r'^tests/download/input-(?P<test_number>[0-9]+)\.txt$', pviews.ProblemTestsTestDataView.as_view(kind='input', download=True), name='test_input_download'),
    url(r'^tests/open/answer-(?P<test_number>[0-9]+)\.txt$', pviews.ProblemTestsTestDataView.as_view(kind='answer', download=False), name='test_answer_open'),
    url(r'^tests/download/answer-(?P<test_number>[0-9]+)\.txt$', pviews.ProblemTestsTestDataView.as_view(kind='answer', download=True), name='test_answer_download'),

    url(r'^solutions/$', pviews.ProblemSolutionsView.as_view(), name='solutions'),
    url(r'^solutions/process/$', pviews.ProblemSolutionsProcessView.as_view(), name='solutions_process'),

    url(r'^files/$', pviews.ProblemFilesView.as_view(), name='files'),
    url(r'^files/data/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', pviews.ProblemFilesFileOpenView.as_view(), name='data_file_open'),
    url(r'^files/data/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', pviews.ProblemFilesFileOpenView.as_view(download=True), name='data_file_download'),
    url(r'^files/data/(?P<file_id>[0-9]+)/edit/$', pviews.ProblemFilesDataFileEditView.as_view(), name='data_file_edit'),
    url(r'^files/data/(?P<file_id>[0-9]+)/delete/$', pviews.ProblemFilesDataFileDeleteView.as_view(), name='data_file_delete'),
    url(r'^files/data/new/$', pviews.ProblemFilesDataFileNewView.as_view(), name='data_file_new'),

    url(r'^files/source/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', pviews.ProblemFilesSourceFileOpenView.as_view(), name='source_file_open'),
    url(r'^files/source/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', pviews.ProblemFilesSourceFileOpenView.as_view(download=True), name='source_file_download'),
    url(r'^files/source/(?P<file_id>[0-9]+)/edit/$', pviews.ProblemFilesSourceFileEditView.as_view(), name='source_file_edit'),
    url(r'^files/source/(?P<file_id>[0-9]+)/delete/$', pviews.ProblemFilesSourceFileDeleteView.as_view(), name='source_file_delete'),
    url(r'^files/source/new/$', pviews.ProblemFilesSourceFileNewView.as_view(), name='source_file_new'),

    url(r'^tex/$', pviews.ProblemTeXView.as_view(), name='tex'),
    url(r'^tex/render/$', pviews.ProblemTeXRenderView.as_view(), name='tex_render'),
    url(r'^tex/new/statement/$', pviews.ProblemTeXNewStatementView.as_view(), name='tex_new_statement'),
    url(r'^tex/new/statement/(?P<filename>.+)$', pviews.ProblemTeXEditorRelatedFileView.as_view()),
    url(r'^tex/new/tutorial/$', pviews.ProblemTeXNewTutorialView.as_view(), name='tex_new_tutorial'),
    url(r'^tex/new/tutorial/(?P<filename>.+)$', pviews.ProblemTeXEditorRelatedFileView.as_view()),
    url(r'^tex/(?P<file_id>[0-9]+)/$', pviews.ProblemTeXEditView.as_view(), name='edit_tex'),
    url(r'^tex/([0-9]+)/(?P<filename>.+)$', pviews.ProblemTeXEditorRelatedFileView.as_view()),

    url(r'^challenges/$', pviews.ProblemChallengesView.as_view(), name='challenges'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/$', pviews.ProblemChallengeView.as_view(), name='challenge'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/add-test/$', pviews.ProblemChallengeAddTestView.as_view(), name='challenge_add_test'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/status/json/$', pviews.ProblemChallengeJsonView.as_view(), name='challenge_status_json'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/open/(?P<resource_id>[0-9a-f]*)/(?P<filename>[a-z0-9\-]+)\.txt$', pviews.ProblemChallengeDataView.as_view(download=False), name='challenge_data_open'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/download/(?P<resource_id>[0-9a-f]*)/(?P<filename>[a-z0-9\-]+)\.txt$', pviews.ProblemChallengeDataView.as_view(download=True), name='challenge_data_download'),
    url(r'^challenges/new/$', pviews.ProblemNewChallengeView.as_view(), name='new_challenge'),

    url(r'^rejudges/$', pviews.ProblemRejudgesView.as_view(), name='rejudges'),

    url(r'^submit/$', pviews.ProblemSubmitView.as_view(), name='submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', pviews.ProblemSubmissionView.as_view(), name='submission'),
    url(r'^folders/$', pviews.ProblemFoldersView.as_view(), name='folders'),
    url(r'^name/$', pviews.ProblemNameView.as_view(), name='name'),
    url(r'^properties/$', pviews.ProblemPropertiesView.as_view(), name='properties'),
    url(r'^pictures/$', pviews.ProblemPicturesView.as_view(), name='pictures'),
    url(r'^validator/$', pviews.ProblemValidatorView.as_view(), name='validator'),
    url(r'^delete/$', pviews.ProblemDeleteView.as_view(), name='delete'),
    url(r'^access/$', pviews.ProblemAccessView.as_view(), name='access'),
    url(r'^edit/$', pviews.ProblemEditView.as_view(), name='edit'),
]

urlpatterns = [
    path('<int:problem_id>/', include(problem_urlpatterns)),
]

project/problems/urls.py
from django.conf.urls import include, url

from problems import views
from problems.folders.urls import urlpatterns as folders_urlpatterns
from problems.problem.urls import urlpatterns as problem_urlpatterns

app_name = 'problems'

urlpatterns = [
    url(r'^$', views.DefaultView.as_view(), name='default'),
    url(r'^tree/$', views.ShowTreeView.as_view(), name='show_tree'),
    url(r'^tree/(?P<folder_id>[0-9]+)/$', views.ShowTreeFolderView.as_view(), name='show_tree_folder'),
    url(r'^tree/(?P<folder_id>[0-9]+)/json/$', views.ShowTreeFolderJsonView.as_view(), name='show_tree_folder_json'),
    url(r'^', include(problem_urlpatterns)),
    url(r'^folders/', include(folders_urlpatterns)),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^access-browser/$', views.AccessBrowserView.as_view(), name='access_browser'),
    url(r'^tex/$', views.TeXView.as_view(), name='tex_playground'),
    url(r'^tex/render/$', views.TeXRenderView.as_view(), name='tex_playground_render'),
]

project/problems/templates/problems/access_browser.html
{% extends "problems/list_base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_problems %}
{% load irunner_users %}

{% block main %}
<ol class="breadcrumb">
    <li>{% trans 'Access browser' %}</li>
</ol>

<h3>{% trans 'Individual access' %}</h3>
<table class="table table-bordered table-condensed ir-table-nonfluid">
<thead>
    <th>{% trans 'Problem' %}</th>
    <th>{% trans 'User' %}</th>
    <th>{% trans 'Mode' %}</th>
    <th></th>
</thead>
<tbody>
{% for entry in individual_access_records %}
    <tr>
        <td>{% irunner_problems_difficulty entry.problem.difficulty %} <a href="{% url 'problems:overview' entry.problem.id %}">{{ entry.problem.numbered_full_name }}</a></td>
        <td>{% irunner_users_card entry.user %}</td>
        <td><span class="badge">{{ entry.get_mode_display }}</span></td>
        <td><a href="{% url 'problems:access' entry.problem.id %}">{% trans 'Edit' %}</a></td>
    </tr>
{% endfor %}
</tbody>
</table>

<h3>{% trans 'Group access' %}</h3>
<table class="table table-bordered table-condensed ir-table-nonfluid">
<thead>
    <th>{% trans 'Folder' %}</th>
    <th>{% trans 'Group' %}</th>
    <th>{% trans 'Mode' %}</th>
    <th></th>
</thead>
<tbody>
{% for entry in group_access_records %}
    <tr>
        <td><a href="{% url 'problems:show_folder' entry.folder.id %}">{{ entry.folder }}</a></td>
        <td>{{ entry.group }}</td>
        <td><span class="badge">{{ entry.get_mode_display }}</span></td>
        <td><a href="{% url 'problems:folder_access' entry.folder.id %}">{% trans 'Edit' %}</a></td>
    </tr>
{% endfor %}
</tbody>
</table>

{% endblock %}

project/problems/templates/problems/irunner_problems_list_tag.html
{% load i18n %}
{% load irunner_problems %}
{% load irunner_pagination %}

<div class="panel panel-default">
    <div class="panel-body">
        {% if problems %}
            {% if pagination_context %}
                {% irunner_pagination pagination_context %}
            {% endif %}

            <table class="table table-condensed">
                <thead>
                    <tr>
                        {% if show_checkbox %}
                            <th class="ir-col-shrink"><input type="checkbox" id="selectall"></th>
                        {% endif %}
                        <th class="ir-col-shrink">{% trans 'Level' %}</th>
                        <th>{% trans 'Name' %}</th>
                        <th class="text-nowrap">{% trans 'Short name' %}</th>
                        <th class="ir-col-shrink text-right">{% trans 'Tests' %}</th>
                        <th class="ir-col-shrink text-right">{% trans 'Solutions' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for problem in problems %}
                    <tr>
                        {% if show_checkbox %}
                            <td class="ir-col-shrink"><input type="checkbox" class="ir-checkbox" name="{{ problem.id }}"></td>
                        {% endif %}
                        <td class="ir-col-shrink">{% irunner_problems_difficulty problem.difficulty %}</td>
                        <td><a href="{% url 'problems:overview' problem.id %}{{ query_string }}">{{ problem.numbered_full_name }}</a></td>
                        <td class="text-nowrap">{{ problem.numbered_short_name }}</td>
                        {% irunner_problems_getinfo problem.id infomanager as info %}
                        <td class="ir-col-shrink text-right">{{ info.test_count }}</td>
                        <td class="ir-col-shrink text-right"><span class="ir-accepted-solution-count">{{ info.accepted_solution_count }}</span>&thinsp;/&thinsp;<span class="ir-all-solution-count">{{ info.all_solution_count }}</span></td>
                        <td class="ir-col-shrink text-left "></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        {% else %}
            <div class="ir-absence">
                {% if list_is_complete %}
                    {% trans 'No problems' %}
                {% else %}
                    {% trans 'No problems available' %}
                {% endif %}
            </div>
        {% endif %}
    </div>
</div>

project/problems/templates/problems/list_folder_confirm_delete.html
{% extends "problems/list_base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_folders %}

{% block sidebar %}
    {% irunner_folders_tree inmemory_tree 'problems:show_folder' folder_id %}
{% endblock %}

{% block main %}
    {% irunner_folders_breadcrumbs inmemory_tree 'problems:show_folder' folder_id %}

    <h3>{% trans 'Delete folder' %}</h3>

    {% if course_list %}
        <p>{% trans 'The folder or its subfolders are currently used in the following courses and cannot be deleted.' %}</p>
        <ul>
            {% for course in course_list %}
                <li>
                    <a href="{% url 'courses:show_course_info' course.id %}">{{ course }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans 'The folder is going to be deleted together with its subfolders. The problems they contain will not be deleted.' %}</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">
                {% trans 'Delete' %}
            </button>
            <a href="{% irunner_folders_url 'problems:show_folder' folder_id %}" class="btn btn-link">
                {% trans 'Cancel' %}
            </a>
        </form>
    {% endif %}
{% endblock %}

project/problems/templates/problems/tree.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans 'Problems' %}{% endblock %}

{% block head %}
    <link href="{% static 'fancytree-2.13.0/skin-win8/ui.fancytree.min.css' %}" rel="stylesheet">
    <link href="{% static 'DataTables-1.10.10/media/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'jquery-ui-1.11.4.custom/jquery-ui.min.js' %}"></script>
    <script src="{% static 'fancytree-2.13.0/jquery.fancytree-all.min.js' %}"></script>
    <script src="{% static 'DataTables-1.10.10/media/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'DataTables-1.10.10/media/js/dataTables.bootstrap.min.js' %}"></script>
{% endblock %}

{% block content %}

{% get_current_language as LANGUAGE_CODE %}

<script>
var irSourceData = {{ tree_data|safe }};

function setFolderHeader(json) {
    var name = json["name"] || "";
    $("#foldername").text(name);

    var id = json["id"];
    if (id) {
        var urlMask = "{% url 'problems:show_tree_folder' 12345 %}".replace(/12345/, id);
        history.pushState({}, name, urlMask);
    }
}

$(document).ready(function() {
    $("#datatable").DataTable({
        "language": {
            "url": "{% static 'DataTables-1.10.10/i18n' %}/{{ LANGUAGE_CODE }}.json"
        },
        "autoWidth": false,
        {% if table_data %}
            "data": {{ table_data|safe }}
        {% endif %}
    });

    var fancyTree = $("#tree").fancytree({
        source: irSourceData
    });

    {% if cur_folder_id %}
        $("#tree").fancytree("getTree").activateKey("{{ cur_folder_id }}");
    {% endif %}

    fancyTree.bind("fancytreeactivate", function(event, data) {
        var node = data.node;
        var urlMask = "{% url 'problems:show_tree_folder_json' 12345 %}".replace(/12345/, node.key.toString());
        $("#datatable").dataTable().api().ajax.url(urlMask).load(setFolderHeader);
    });
});
</script>

<div class="row">
    <div class="col-md-3">
        <div id="tree"></div>
    </div>
    <div class="col-md-9">
        <h3 id="foldername">{{ cur_folder_name }}</h3>
        <table id="datatable" class="table table-striped table-condensed table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Full Name</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

{% endblock %}