project/api/urls.py
from django.conf.urls import url

from . import views
from contests.globalviews import ContestsApiView

app_name = 'api'

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view()),
    url(r'^fs/(?P<filename>new)$', views.NewFileView.as_view()),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/cancel$', views.JobCancelView.as_view()),
    url(r'^compiler-settings$', views.CompilerSettingsView.as_view()),
    url(r'^plagiarism/take$', views.PlagiarismTakeView.as_view()),
    url(r'^plagiarism/put$', views.PlagiarismPutView.as_view()),
    url(r'^sleep$', views.SleepView.as_view()),
    url(r'^printing$', views.PrintingView.as_view()),
    url(r'^printing/(?P<printout_id>\d+)$', views.PrintingDoneView.as_view()),
    url(r'^auth/check$', views.AuthCheckView.as_view()),
    url(r'^contests$', ContestsApiView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/courses/settings/urls.py
from django.conf.urls import url

from courses.settings import views as settingsviews


settings_urlpatterns = ([
    url(r'^$', settingsviews.CourseSettingsPropertiesView.as_view(), name='properties'),

    url(r'^delete/$', settingsviews.CourseSettingsDeleteView.as_view(), name='delete'),
    url(r'^clone/$', settingsviews.CourseSettingsCloneView.as_view(), name='clone'),

    url(r'^access/$', settingsviews.CourseSettingsAccessView.as_view(), name='access'),

    url(r'^problems/$', settingsviews.CourseSettingsProblemsView.as_view(), name='problems'),
    url(r'^problems/topics/create/$', settingsviews.CourseSettingsTopicsCreateView.as_view(), name='topics_create'),
    url(r'^problems/topics/(?P<pk>[0-9]+)/$', settingsviews.CourseSettingsTopicsUpdateView.as_view(), name='topics_update'),
    url(r'^problems/topics/(?P<topic_id>[0-9]+)/common/$', settingsviews.CourseSettingsTopicCommonProblemsView.as_view(), name='topic_common_problems'),
    url(r'^problems/common/$', settingsviews.CourseSettingsCommonProblemsView.as_view(), name='common_problems'),
    url(r'^problems/list/(?P<folder_id>[^/]+)/$', settingsviews.CourseSettingsProblemsJsonListView.as_view(), name='problems_json_list'),

    url(r'^sheet/$', settingsviews.CourseSettingsSheetActivityListView.as_view(), name='sheet'),
    url(r'^sheet/activities/create/$', settingsviews.CourseSettingsSheetActivityCreateView.as_view(), name='sheet_activity_create'),
    url(r'^sheet/activities/(?P<pk>[0-9]+)/$', settingsviews.CourseSettingsSheetActivityUpdateView.as_view(), name='sheet_activity_update'),

    url(r'^subgroups/$', settingsviews.CourseSettingsSubgroupListView.as_view(), name='subgroups'),
    url(r'^subgroups/new/$', settingsviews.CourseSettingsSubgroupCreateView.as_view(), name='subgroup_create'),
    url(r'^subgroups/(?P<pk>[0-9]+)/$', settingsviews.CourseSettingsSubgroupUpdateView.as_view(), name='subgroup_update'),

    url(r'^users/$', settingsviews.CourseSettingsUsersView.as_view(), name='users'),
    url(r'^users/students/$', settingsviews.CourseSettingsUsersStudentsView.as_view(), name='users_students'),
    url(r'^users/teachers/$', settingsviews.CourseSettingsUsersTeachersView.as_view(), name='users_teachers'),
    url(r'^users/list/(?P<folder_id>[^/]+)/$', settingsviews.CourseSettingsUsersJsonListView.as_view(), name='users_json_list'),

    url(r'^compilers/$', settingsviews.CourseSettingsCompilersView.as_view(), name='compilers'),

    url(r'^quizzes/$', settingsviews.CourseSettingsQuizzesView.as_view(), name='quizzes'),
    url(r'^quizzes/create/$', settingsviews.CourseSettingsQuizzesCreateView.as_view(), name='quizzes_create'),
    url(r'^quizzes/(?P<instance_id>[0-9]+)/$', settingsviews.CourseSettingsQuizzesUpdateView.as_view(), name='quizzes_update'),

    url(r'^queues/$', settingsviews.CourseSettingsQueuesView.as_view(), name='queues'),
    url(r'^queues/create/$', settingsviews.CourseSettingsQueueCreateView.as_view(), name='queue_create'),
    url(r'^queues/(?P<pk>[0-9]+)/$', settingsviews.CourseSettingsQueueUpdateView.as_view(), name='queue_update'),
], 'settings')

project/courses/urls.py
from django.conf.urls import url, include
from django.urls import path

from courses.settings.urls import settings_urlpatterns
from . import views, globalviews, assignviews, problemviews, quizviews, queueviews

app_name = 'courses'

quiz_urlpatterns = ([
    url(r'^$', quizviews.CourseQuizzesView.as_view(), name='list'),
    url(r'^sessions/(?P<session_id>[0-9]+)/$', quizviews.CourseQuizzesSessionView.as_view(), name='session'),
    url(r'^sessions/(?P<session_id>[0-9]+)/answers/$', quizviews.CourseQuizzesAnswersView.as_view(), name='answers'),
    url(r'^sessions/(?P<session_id>[0-9]+)/answers/api/$', quizviews.CourseQuizzesSaveMarkView.as_view(), name='save_mark'),
    url(r'^sessions/(?P<session_id>[0-9]+)/finish/$', quizviews.CourseQuizzesFinishView.as_view(), name='finish'),
    url(r'^sessions/(?P<session_id>[0-9]+)/save-answer/$', quizviews.SaveAnswerAPIView.as_view(), name='save_answer'),
    url(r'^sessions/(?P<session_id>[0-9]+)/delete/$', quizviews.CourseQuizzesDeleteSessionView.as_view(),
        name='delete_session'),
    url(r'^sessions/(?P<session_id>[0-9]+)/submit-comment/$', quizviews.CourseQuizzesSubmitCommentView.as_view(),
        name='submit_comment'),
    url(r'^start/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesStartView.as_view(), name='start'),
    url(r'^rating/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesRatingView.as_view(), name='rating'),
    url(r'^sheet/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesSheetView.as_view(), name='sheet'),
    url(r'^turn-on/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesTurnOnView.as_view(), name='turn_on'),
    url(r'^turn-off/(?P<instance_id>[0-9]+)/$', quizviews.CourseQuizzesTurnOffView.as_view(), name='turn_off'),
], 'quizzes')

queue_urlpatterns = ([
    url(r'^$', queueviews.ListView.as_view(), name='list'),
    url(r'^(?P<queue_id>[0-9]+)/add/$', queueviews.AddView.as_view(), name='add'),
    url(r'^(?P<queue_id>[0-9]+)/join/$', queueviews.JoinView.as_view(), name='join'),
    url(r'^(?P<queue_id>[0-9]+)/items/(?P<item_id>[0-9]+)/start/$', queueviews.StartView.as_view(), name='start'),
    url(r'^(?P<queue_id>[0-9]+)/items/(?P<item_id>[0-9]+)/finish/$', queueviews.FinishView.as_view(), name='finish'),
], 'queues')

assignment_urlpatterns = ([
    url(r'^$', assignviews.CourseEmptyAssignView.as_view(), name='empty'),
    url(r'^(?P<user_id>[0-9]+)/$', assignviews.CourseAssignView.as_view(), name='index'),
    url(r'^(?P<user_id>[0-9]+)/new-penalty/$', assignviews.CourseAssignCreatePenaltyProblem.as_view(), name='new_penalty'),
    url(r'^(?P<user_id>[0-9]+)/delete-penalty/(?P<assignment_id>[0-9]+)/$',
        assignviews.CourseAssignDeletePenaltyProblem.as_view(), name='delete_penalty'),
    url(r'^(?P<user_id>[0-9]+)/api/problem/$',
        assignviews.CourseAssignProblemApiView.as_view(), name='api_problem'),
    url(r'^(?P<user_id>[0-9]+)/api/criterion/$',
        assignviews.CourseAssignCriterionApiView.as_view(), name='api_criterion'),
    url(r'^(?P<user_id>[0-9]+)/api/topic-problems/(?P<topic_id>[0-9]+)/$',
        assignviews.ListTopicProblemsApiView.as_view()),
], 'assignment')

problem_urlpatterns = [
    url(r'^problemset/$', problemviews.EmptyView.as_view(), name='course_problems'),
    url(r'^problemset/(?P<topic_id>[0-9]+)/$', problemviews.FullTopicListView.as_view(), name='course_problems_topic'),
    url(r'^problemset/(?P<topic_id>[0-9]+)/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', problemviews.TopicItemView.as_view(), name='course_problems_topic_problem'),
    url(r'^problemset/(?P<topic_id>[0-9]+)/common/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', problemviews.TopicCommonProblemsItemView.as_view(), name='course_problems_topic_common_problem'),
    url(r'^problemset/common/$', problemviews.CommonProblemsListView.as_view(), name='course_common_problems'),
    url(r'^problemset/common/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', problemviews.CommonProblemsItemView.as_view(), name='course_common_problems_problem'),
    url(r'^problems/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', problemviews.AnyProblemView.as_view(), name='course_problems_problem'),
]

single_course_urlpatterns = [
    url(r'^$', views.CourseInfoView.as_view(), name='show_course_info'),
    url(r'^standings/$', views.CourseStandingsView.as_view(), name='course_standings'),
    url(r'^standings/wide/$', views.CourseStandingsWideView.as_view(), name='course_standings_wide'),
    url(r'^sheet/$', views.CourseSheetView.as_view(), name='course_sheet'),
    url(r'^sheet/edit/$', views.CourseSheetEditView.as_view(), name='course_sheet_edit'),
    url(r'^sheet/edit/api/(?P<membership_id>[0-9]+)/(?P<activity_id>[0-9]+)/$',
        views.CourseSheetEditApiView.as_view(), name='course_sheet_edit_api'),
    url(r'^compilers/$', views.CourseCompilersView.as_view(), name='course_compilers'),

    url(r'^submit/$', views.CourseSubmit2View.as_view(), name='course_submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.CourseSubmissionView.as_view(), name='course_submission'),

    url(r'^solutions/$', views.CourseAllSolutionsView.as_view(), name='all_solutions'),
    url(r'^my/solutions/$', views.CourseMySolutionsView.as_view(), name='my_solutions'),

    url(r'^my/problems/$', views.CourseMyProblemsView.as_view(), name='my_problems'),

    url(r'^my/attempts/$', views.CourseMyAttemptsView.as_view(), name='my_attempts'),
    url(r'^blocked/$', views.CourseBlockedView.as_view(), name='blocked'),

    # Messages

    url(r'^mailbox/$', views.CourseMessagesEmptyView.as_view(), name='messages_empty'),
    url(r'^mailbox/(?P<thread_id>[0-9]+)/$', views.CourseMessagesView.as_view(), name='messages'),
    url(r'^mailbox/(?P<thread_id>[0-9]+)/delete/$', views.CourseMessagesThreadDeleteView.as_view(), name='messages_thread_delete'),
    url(r'^mailbox/(?P<thread_id>[0-9]+)/resolve/$', views.CourseMessagesThreadResolveView.as_view(), name='messages_thread_resolve'),
    url(r'^mailbox/(?P<thread_id>[0-9]+)/messages/(?P<message_id>[0-9]+)/attachment/(?P<filename>.*)$',
        views.CourseMessagesDownloadView.as_view(), name='messages_download'),
    url(r'^mailbox/new/$', views.CourseMessagesNewView.as_view(), name='messages_new'),

    url(r'^quizzes/', include(quiz_urlpatterns)),
    url(r'^queues/', include(queue_urlpatterns)),
    url(r'^settings/', include(settings_urlpatterns)),
    url(r'^assign/', include(assignment_urlpatterns)),

    path('', include(problem_urlpatterns)),
]

urlpatterns = [
    url(r'^$', globalviews.ActiveCourseListView.as_view(), name='index'),
    url(r'^all/$', globalviews.AllCourseListView.as_view(), name='index_all'),
    url(r'^my/$', globalviews.MyCourseListView.as_view(), name='my'),
    url(r'^new/$', globalviews.CourseCreateView.as_view(), name='new'),

    url(r'^criteria/$', views.CriterionListView.as_view(), name='criterion_index'),
    url(r'^criteria/new/$', views.CriterionCreateView.as_view(), name='criterion_new'),
    url(r'^criteria/(?P<pk>[0-9]+)/edit/$', views.CriterionUpdateView.as_view(), name='criterion_edit'),
    url(r'^criteria/(?P<pk>[0-9]+)/delete/$', views.CriterionDeleteView.as_view(), name='criterion_delete'),

    url(r'^(?P<course_id>[0-9]+)/', include(single_course_urlpatterns)),
]

project/solutions/urls.py
from django.conf.urls import include, url

from .halloffame import views as hviews
from .activity import views as aviews
from .challenges import views as chviews
from .compare import views as cmpviews

from .solution.urls import urlpatterns as solution_urlpatterns
from .solutions.urls import urlpatterns as solutions_urlpatterns
from .judgement.urls import urlpatterns as judgement_urlpatterns
from .rejudge.urls import urlpatterns as rejudges_urlpatterns

app_name = 'solutions'

urlpatterns = [
    url(r'^solutions/', include(solution_urlpatterns + solutions_urlpatterns)),
    url(r'^solutions/compare/$', cmpviews.CompareSolutionsView.as_view(), name='compare'),
    url(r'^runs/', include(judgement_urlpatterns)),
    url(r'^rejudges/', include(rejudges_urlpatterns)),
    url(r'^challenges/$', chviews.ChallengeListView.as_view(), name='challenge_list'),
    url(r'^hall-of-fame/$', hviews.HallOfFameView.as_view(), name='hall_of_fame'),
    url(r'^activity/$', aviews.ActivityView.as_view(), name='activity'),
]

project/solutions/activity/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import datetime

from django.db.models.functions import TruncDay
from django.db.models import Count, F, Q
from django.shortcuts import render
from django.utils import timezone
from django.views import generic

from common.outcome import Outcome
from common.statutils import build_proglangbars, build_outcomebars

from solutions.models import Solution, Judgement


class SingleDayInfo(object):
    def __init__(self, date):
        self.date = date
        self.accepted = 0
        self.rejected = 0
        self._max_value = None

    def set_max_value(self, max_value):
        self._max_value = max_value if max_value > 0 else 1

    @staticmethod
    def _perc(x):
        return '{:.2f}%'.format(x)

    def get_accepted_perc(self):
        return self._perc(100. * self.accepted / self._max_value)

    def get_all_perc(self):
        return self._perc(100. * (self.accepted + self.rejected) / self._max_value)


def _make_solutions_qs(qs, start_date):
    assert isinstance(start_date, datetime.date)
    start_datetime = datetime.datetime.combine(start_date, datetime.time.min)
    ts = timezone.make_aware(start_datetime)

    first_id = qs.\
        filter(reception_time__gte=ts).\
        values_list('id', flat=True).\
        first()

    if first_id is not None:
        return qs.filter(id__gte=first_id)
    return qs.none()


def _make_chart(queryset, start_date, end_date):
    day = datetime.timedelta(days=1)
    mp = {}
    results = []
    today = start_date
    while (today <= end_date) and (len(results) <= 1000):
        info = SingleDayInfo(today)
        results.append(info)
        mp[today] = info
        today += day

    tzinfo = timezone.get_current_timezone()
    for day, num_accepted, num_rejected in queryset.\
            filter(best_judgement__status=Judgement.DONE).\
            annotate(
                day=TruncDay('reception_time', tzinfo=tzinfo),
                outcome=F('best_judgement__outcome')
            ).\
            values_list('day').\
            annotate(
                num_accepted=Count('pk', filter=Q(outcome=Outcome.ACCEPTED)),
                num_rejected=Count('pk', filter=~Q(outcome=Outcome.ACCEPTED))
            ).\
            values_list('day', 'num_accepted', 'num_rejected'):

        info = mp.get(day.date())
        if info is not None:
            info.accepted += num_accepted
            info.rejected += num_rejected

    max_value = 0
    for info in results:
        max_value = max(max_value, info.accepted + info.rejected)
    for info in results:
        info.set_max_value(max_value)
    return results


def _get_term_start(today):
    assert isinstance(today, datetime.date)
    if today.month >= 9:
        term_start = datetime.date(today.year, 9, 1)
    elif today.month <= 1:
        term_start = datetime.date(today.year - 1, 9, 1)
    else:
        term_start = datetime.date(today.year, 2, 1)
    return term_start


class ActivityView(generic.View):
    template_name = 'solutions/activity.html'
    bar_max_px = 16

    def get(self, request):
        ts = timezone.now()
        today = timezone.localtime(ts).date()

        year_start = today - datetime.timedelta(days=365)
        year_solution_queryset = _make_solutions_qs(Solution.objects, year_start)
        results_year = _make_chart(year_solution_queryset, year_start, today)

        term_start = _get_term_start(today)
        term_solution_queryset = _make_solutions_qs(Solution.objects, term_start).filter(coursesolution__isnull=False)
        results_term = _make_chart(term_solution_queryset, term_start, today)

        all_proglangbars = build_proglangbars(term_solution_queryset)
        accepted_proglangbars = build_proglangbars(term_solution_queryset.filter(best_judgement__status=Judgement.DONE, best_judgement__outcome=Outcome.ACCEPTED))

        outcomebars = build_outcomebars(term_solution_queryset)

        context = {
            'results_year': results_year,
            'results_term': results_term,
            'max_width_px': self.bar_max_px * len(results_term),
            'term_start': term_start,
            'all_proglangbars': all_proglangbars,
            'accepted_proglangbars': accepted_proglangbars,
            'outcomebars': outcomebars,
        }
        return render(request, self.template_name, context)

project/solutions/challenges/views.py
from django.db.models import Count

from common.pagination.views import IRunnerListView
from cauth.mixins import ProblemEditorMemberRequiredMixin
from problems.calcpermissions import get_problem_ids_queryset, has_limited_problems_queryset

from solutions.models import Challenge

'''
Global challenges list
'''


class ChallengeListView(ProblemEditorMemberRequiredMixin, IRunnerListView):
    template_name = 'solutions/challenge_list.html'

    def get_queryset(self):
        qs = Challenge.objects.\
            annotate(num_solutions=Count('challengedsolution')).\
            select_related('problem').\
            order_by('-creation_time', '-id').\
            all()
        if has_limited_problems_queryset(self.request.user):
            qs = qs.filter(problem_id__in=get_problem_ids_queryset(self.request.user))
        return qs

project/courses/templates/courses/irunner_courses_slotresult_tag.html
{% load bootstrap3 %}
{% load i18n %}
{% load irunner_courses %}
{% load irunner_problems %}
{% load irunner_proglangs %}
{% load irunner_solutions %}

{# variables in context: slot_result, problem_result #}

<div
    class="ir-slot-result"
    {% if slot_result %}
        {% if slot_result.slot %} data-slot="{{ slot_result.slot.id }}"{% endif %}
        {% if slot_result.assignment %} data-assignment="{{ slot_result.assignment.id }}"{% endif %}
        data-topic="{{ slot_result.topic_descr.topic.id }}"
    {% endif %}
>
    <div class="row">
        <div class="col-sm-9">
            <div>
                {% if problem_result %}
                    {% irunner_problems_difficulty problem_result.problem.difficulty %}
                    <a href="{% url 'courses:course_problems_problem' course_id problem_result.problem.id %}" title="{% trans 'Statement' %}">{{ problem_result.problem.numbered_full_name }}</a>
                {% else %}
                    <span class="ir-absence">{% trans 'No problem is assigned' %}</span>
                {% endif %}
                {% if editable %}
                    <button type="button" class="btn btn-xs btn-default ir-assign-button" title="{% trans 'Assign' %}">{% bootstrap_icon 'pencil' %}</button>
                {% endif %}
            </div>
            {% if problem_result %}
                {% if problem_result.best_solution and solution_permissions.can_view_state %}
                    <div class="ir-best-solution">
                        {% url 'solutions:main' problem_result.best_solution.id as s_url %}
                        {% url 'solutions:source' problem_result.best_solution.id as c_url %}
                        <a href="{{ s_url }}">{% irunner_solutions_judgementbox problem_result.best_solution.best_judgement tooltip=True %}</a>
                        <a href="{{ s_url }}">{% irunner_solutions_scorebox problem_result.best_solution.best_judgement %}</a>
                        {% if solution_permissions.can_view_source_code %}
                            <a href="{{ c_url }}">{% irunner_proglangs_compilerbox problem_result.best_solution.compiler tooltip=True %}</a>
                        {% else %}
                            {% irunner_proglangs_compilerbox problem_result.best_solution.compiler tooltip=True %}
                        {% endif %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <div class="col-sm-3">
            {% if slot_result %}
                {% for criterion_descr in slot_result.criterion_descrs %}
                    <div {% if editable %} class="ir-toggle-criterion"{% endif %}>
                        {% irunner_courses_criterion criterion_descr.criterion criterion_descr.ok editable=editable %}
                        {{ criterion_descr.criterion.name }}
                    </div>
                {% endfor %}
            {% endif %}
            {% if problem_result %}
            <div>
                <div class="ir-box ir-criterion ir-criterion-{{ problem_result.is_ok|yesno:"yes,no" }}"><span class="invisible">&nbsp;</span></div>
                {% if problem_result.solutions %}
                    {% with solution_permissions.can_view_state as make_link %}
                    {% with problem_result.solutions|length as cnt %}
                        {% if make_link %}<a href="{% if user_id %}{% url 'courses:all_solutions' course_id %}?user={{ user_id }}&amp;problem={{ problem_result.problem.id }}{% else %}{% url 'courses:my_solutions' course_id %}?problem={{ problem_result.problem.id }}{% endif %}">{% endif %}{{ cnt }}&nbsp;{% blocktrans count counter=cnt %}solution{% plural %}solutions{% endblocktrans %}{% if make_link %}</a>{% endif %}
                    {% endwith %}
                    {% endwith %}
                {% else %}
                    {% trans 'No solutions' %}
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>

project/courses/templates/courses/sidebar.html
{% load bootstrap3 %}
{% load i18n %}

<div class="list-group">
    {% if permissions.info %}
        <a href="{% url 'courses:show_course_info' course.id %}" class="list-group-item list-group-item-info{% if active_tab == 'info' %} active{% endif %}">
            {% bootstrap_icon 'info-sign' %}
            <span class="ir-icon-label">{{ course }}</span>
        </a>
    {% endif %}

    {% if course_is_archived %}
        <a class="list-group-item list-group-item-warning">
            {% bootstrap_icon 'lock' %}
            <span class="ir-icon-label"><em>{% trans 'Archived' %}</em></span>
        </a>
    {% endif %}

    {% if permissions.problems %}
        <a href="{% url 'courses:course_problems' course.id %}" class="list-group-item{% if active_tab == 'problems' %} active{% endif %}">
            {% bootstrap_icon 'th' %}
            <span class="ir-icon-label">{% trans 'Course problems' %}</span>
        </a>
    {% endif %}

    {% if permissions.my_problems %}
        <a href="{% url 'courses:my_problems' course.id %}" class="list-group-item{% if active_tab == 'my_problems' %} active{% endif %}">
            {% bootstrap_icon 'th-large' %}
            <span class="ir-icon-label">{% trans 'My problems' %}</span>
        </a>
    {% endif %}

    {% if permissions.messages %}
        <a href="{% url 'courses:messages_empty' course.id %}" class="list-group-item{% if active_tab == 'messages' %} active{% endif %}">
            {% bootstrap_icon 'envelope' %}
            <span class="ir-icon-label">{% trans 'Messages' %}</span>
            {% if unread %}<span class="badge">{{ unread }}</span>{% endif %}
        </a>
    {% endif %}

    {% if permissions.assign %}
        <a href="{% url 'courses:assignment:empty' course.id %}" class="list-group-item{% if active_tab == 'assign' %} active{% endif %}">
            {% bootstrap_icon 'link' %}
            <span class="ir-icon-label">{% trans 'Assignment of problems' %}</span>
        </a>
    {% endif %}

    {% if permissions.standings %}
        <a href="{% url 'courses:course_standings' course.id %}" class="list-group-item{% if active_tab == 'standings' %} active{% endif %}">
            {% bootstrap_icon 'book' %}
            <span class="ir-icon-label">{% trans 'Standings' context 'course' %}</span>
        </a>
    {% endif %}

    {% if permissions.sheet %}
        <a href="{% url 'courses:course_sheet' course.id %}" class="list-group-item{% if active_tab == 'sheet' %} active{% endif %}">
            {% bootstrap_icon 'list-alt' %}
            <span class="ir-icon-label">{% trans 'Sheet' %}</span>
        </a>
    {% endif %}

    {% if permissions.all_solutions %}
        <a href="{% url 'courses:all_solutions' course.id %}" class="list-group-item{% if active_tab == 'all_solutions' %} active{% endif %}">
            {% bootstrap_icon 'tasks' %}
            <span class="ir-icon-label">{% trans 'All solutions' %}</span>
        </a>
    {% endif %}

    {% if permissions.my_solutions %}
        <a href="{% url 'courses:my_solutions' course.id %}" class="list-group-item{% if active_tab == 'my_solutions' %} active{% endif %}">
            {% bootstrap_icon 'tasks' %}
            <span class="ir-icon-label">{% trans 'My solutions' %}</span>
        </a>
    {% endif %}

    {% if permissions.submit %}
        <a href="{% url 'courses:course_submit' course.id %}" class="list-group-item{% if active_tab == 'submit' %} active{% endif %}">
            {% bootstrap_icon 'send' %}
            <span class="ir-icon-label">{% trans 'Submit solution' %}</span>
        </a>
    {% endif %}

    {% if permissions.info %}
        <a href="{% url 'courses:course_compilers' course.id %}" class="list-group-item{% if active_tab == 'compilers' %} active{% endif %}">
            {% bootstrap_icon 'pushpin' %}
            <span class="ir-icon-label">{% trans 'Compilers' %}</span>
        </a>
    {% endif %}

    {% if permissions.info %}
        <a href="{% url 'courses:quizzes:list' course.id %}" class="list-group-item{% if active_tab == 'quizzes' %} active{% endif %}">
            {% bootstrap_icon 'question-sign' %}
            <span class="ir-icon-label">{% trans 'Quizzes' %}</span>
        </a>
    {% endif %}

    {% if permissions.queue %}
        <a href="{% url 'courses:queues:list' course.id %}" class="list-group-item{% if active_tab == 'queue' %} active{% endif %}">
            {% bootstrap_icon 'retweet' %}
            <span class="ir-icon-label">{% trans 'Electronic queue' %}</span>
        </a>
    {% endif %}

    {% if permissions.settings %}
        <a href="{% url 'courses:settings:properties' course.id %}" class="list-group-item{% if active_tab == 'settings' %} active{% endif %}">
            {% bootstrap_icon 'cog' %}
            <span class="ir-icon-label">{% trans 'Settings' %}</span>
        </a>
    {% endif %}
</div>