project/api/urls.py
from django.conf.urls import url

from . import views
from contests.globalviews import ContestsApiView

app_name = 'api'

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view()),
    url(r'^fs/(?P<filename>new)$', views.NewFileView.as_view()),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/cancel$', views.JobCancelView.as_view()),
    url(r'^compiler-settings$', views.CompilerSettingsView.as_view()),
    url(r'^plagiarism/take$', views.PlagiarismTakeView.as_view()),
    url(r'^plagiarism/put$', views.PlagiarismPutView.as_view()),
    url(r'^sleep$', views.SleepView.as_view()),
    url(r'^printing$', views.PrintingView.as_view()),
    url(r'^printing/(?P<printout_id>\d+)$', views.PrintingDoneView.as_view()),
    url(r'^auth/check$', views.AuthCheckView.as_view()),
    url(r'^contests$', ContestsApiView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/contests/urls.py
from django.conf.urls import include, url

from . import views, globalviews, settingsviews

app_name = 'contests'

contest_urlpatterns = [
    url(r'^$', views.GeneralView.as_view()),
    url(r'^standings/$', views.StandingsView.as_view(), name='standings'),
    url(r'^standings/wide/$', views.StandingsView.as_view(wide=True), name='standings_wide'),
    url(r'^standings/raw/$', views.StandingsView.as_view(raw=True), name='standings_raw'),
    url(r'^statements/(?P<filename>.+)$', views.StatementsFileView.as_view(), name='statements'),
    url(r'^problems/$', views.ProblemsView.as_view(), name='problems'),
    url(r'^problems/(?P<problem_id>[0-9]+)/$', views.ProblemView.as_view(), name='problem'),
    url(r'^problems/(?P<problem_id>[0-9]+)/(?P<filename>.+)$', views.ProblemFileView.as_view(), name='problem_file'),
    url(r'^solutions/$', views.AllSolutionsView.as_view(), name='all_solutions'),
    url(r'^my/solutions/$', views.MySolutionsView.as_view(), name='my_solutions'),
    url(r'^submit/$', views.SubmitView.as_view(), name='submit'),
    url(r'^attempts/$', views.AttemptsView.as_view(), name='attempts'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.SubmissionView.as_view(), name='submission'),
    url(r'^messages/$', views.MessagesView.as_view(), name='messages'),
    url(r'^messages/new/$', views.NewMessageView.as_view(), name='messages_new'),
    url(r'^messages/(?P<message_id>[0-9]+)/edit/$', views.EditMessageView.as_view(), name='messages_edit'),
    url(r'^messages/(?P<message_id>[0-9]+)/delete/$', views.DeleteMessageView.as_view(), name='messages_delete'),
    url(r'^questions/$', views.AllQuestionsView.as_view(), name='all_questions'),
    url(r'^questions/(?P<message_id>[0-9]+)/$', views.AllQuestionsAnswersView.as_view(), name='all_questions_answers'),
    url(r'^questions/(?P<message_id>[0-9]+)/delete/$', views.AllQuestionsDeleteView.as_view(), name='all_questions_delete'),
    url(r'^my/questions/$', views.MyQuestionsView.as_view(), name='my_questions'),
    url(r'^my/questions/(?P<message_id>[0-9]+)/$', views.MyQuestionsAnswersView.as_view(), name='my_questions_answers'),
    url(r'^my/questions/new/$', views.MyQuestionsNewView.as_view(), name='my_questions_new'),
    url(r'^compilers/$', views.CompilersView.as_view(), name='compilers'),
    url(r'^export/$', views.ExportView.as_view(), name='export'),
    url(r'^export/S4RiS-StanD\.json$', views.S4RiSExportView.as_view(), name='export_s4ris'),
    url(r'^export/ejudge\.xml$', views.EjudgeExportView.as_view(), name='export_ejudge'),
    url(r'^printing/$', views.PrintingView.as_view(), name='printing'),
    url(r'^printouts/new/$', views.NewPrintoutView.as_view(), name='new_printout'),
    url(r'^printouts/(?P<printout_id>[0-9]+)/$', views.ShowPrintoutView.as_view(), name='show_printout'),
    url(r'^printouts/(?P<printout_id>[0-9]+)/edit/$', views.EditPrintoutView.as_view(), name='edit_printout'),
]

contestsettings_urlpatterns = [
    url(r'^$', settingsviews.PropertiesView.as_view(), name='settings_properties'),
    url(r'^access/$', settingsviews.AccessView.as_view(), name='settings_access'),
    url(r'^limits/$', settingsviews.LimitsView.as_view(), name='settings_limits'),
    url(r'^delete/$', settingsviews.DeleteView.as_view(), name='settings_delete'),
    url(r'^compilers/$', settingsviews.CompilersView.as_view(), name='settings_compilers'),
    url(r'^problems/$', settingsviews.ProblemsView.as_view(), name='settings_problems'),
    url(r'^statements/$', settingsviews.StatementsView.as_view(), name='settings_statements'),
    url(r'^problems/list/(?P<folder_id>[^/]+)/$', settingsviews.ProblemsJsonListView.as_view(), name='settings_problems_json_list'),
    url(r'^users/$', settingsviews.UsersView.as_view(), name='settings_users'),
    url(r'^users/(?P<tag>[a-z]+)/$', settingsviews.UserRoleView.as_view(), name='settings_user_role'),
    url(r'^users/list/(?P<folder_id>[^/]+)/$', settingsviews.UsersJsonListView.as_view(), name='settings_users_json_list'),
    url(r'^filters/$', settingsviews.UsersFilterVew.as_view(), name='settings_filters'),
    url(r'^printing/$', settingsviews.PrintingView.as_view(), name='settings_printing'),
]

urlpatterns = [
    url(r'^$', globalviews.ContestListView.as_view(), name='index'),
    url(r'^my/$', globalviews.MyContestListView.as_view(), name='my'),
    url(r'^new/$', globalviews.ContestCreateView.as_view(), name='new'),

    url(r'^(?P<contest_id>[0-9]+)/', include(contest_urlpatterns)),
    url(r'^(?P<contest_id>[0-9]+)/settings/', include(contestsettings_urlpatterns)),
]

project/problems/folders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<folder_id_or_root>[^/]+)/$', views.ShowFolderView.as_view(), name='show_folder'),
    url(r'^(?P<folder_id_or_root>[^/]+)/new/folder/$', views.CreateFolderView.as_view(), name='create_folder'),
    url(r'^(?P<folder_id_or_root>[^/]+)/new/problem/$', views.CreateProblemView.as_view(), name='create_problem'),
    url(r'^(?P<folder_id_or_root>[^/]+)/properties/$', views.UpdateFolderView.as_view(), name='folder_properties'),
    url(r'^(?P<folder_id_or_root>[^/]+)/access/$', views.FolderAccessView.as_view(), name='folder_access'),
    url(r'^(?P<folder_id_or_root>[^/]+)/delete/$', views.DeleteFolderView.as_view(), name='delete_folder'),
    url(r'^(?P<folder_id_or_root>[^/]+)/import-from-polygon/$', views.ImportFromPolygonView.as_view(), name='import_from_polygon'),
]

project/problems/urls.py
from django.conf.urls import include, url

from problems import views
from problems.folders.urls import urlpatterns as folders_urlpatterns
from problems.problem.urls import urlpatterns as problem_urlpatterns

app_name = 'problems'

urlpatterns = [
    url(r'^$', views.DefaultView.as_view(), name='default'),
    url(r'^tree/$', views.ShowTreeView.as_view(), name='show_tree'),
    url(r'^tree/(?P<folder_id>[0-9]+)/$', views.ShowTreeFolderView.as_view(), name='show_tree_folder'),
    url(r'^tree/(?P<folder_id>[0-9]+)/json/$', views.ShowTreeFolderJsonView.as_view(), name='show_tree_folder_json'),
    url(r'^', include(problem_urlpatterns)),
    url(r'^folders/', include(folders_urlpatterns)),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^access-browser/$', views.AccessBrowserView.as_view(), name='access_browser'),
    url(r'^tex/$', views.TeXView.as_view(), name='tex_playground'),
    url(r'^tex/render/$', views.TeXRenderView.as_view(), name='tex_playground_render'),
]

project/contests/views.py
import re

from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.db import transaction, IntegrityError
from django.db.models import F, Q
from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.utils.translation import ugettext, pgettext
from django.views import generic

from common.cast import make_int_list_quiet
from common.constants import make_empty_select, EMPTY_SELECT
from common.networkutils import redirect_with_query_string
from common.pagination import paginate
from problems.models import Problem
from problems.views import ProblemStatementMixin
from solutions.filters import apply_state_filter
from solutions.forms import AllSolutionsFilterForm
from solutions.models import Solution
from solutions.submit.views import SubmitAPIMixin, AttemptsLeftAPIMixin
from solutions.utils import new_solution, judge
from storage.utils import serve_resource_metadata
from users.models import UserProfile

from .calcpermissions import ContestMemberFlags, calculate_contest_permissions
from .exporting import export_to_s4ris_json, export_to_ejudge_xml
from .forms import SolutionListUserForm, SolutionListProblemForm, ContestSolutionForm, MessageForm, AnswerForm, QuestionForm
from .forms import PrintoutForm, EditPrintoutForm
from .models import Contest, ContestSolution, Message, MessageUser, Printout, ContestUserRoom, ContestProblem
from .services import make_contestant_choices, make_problem_choices, make_letter
from .services import ProblemResolver, ContestTiming, ContestAttemptLimitPolicy
from .services import create_contest_service


class BaseContestView(generic.View):
    tab = None
    subtab = None

    def __init__(self, *args, **kwargs):
        super(BaseContestView, self).__init__(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            'contest': self.contest,
            'timing': self.timing,
            'permissions': self.permissions,
            'active_tab': self.tab,
            'active_subtab': self.subtab,
        }
        self._fill_unread_counters(context)
        context.update(kwargs)
        return context

    def _fill_unread_counters(self, context):
        me = self.request.user
        if not me.is_authenticated:
            return

        if self.permissions.read_messages or self.permissions.manage_messages:
            qs = Message.objects.filter(contest=self.contest, message_type=Message.MESSAGE)
            if not self.permissions.manage_messages:
                qs = qs.filter(Q(recipient=me) | Q(recipient__isnull=True))

            # TODO: less queries?
            all_count = qs.count()
            read_count = qs.filter(messageuser__user=me).count()
            context['unread_messages'] = all_count - read_count

        if self.permissions.answer_questions:
            qs = Message.objects.filter(contest=self.contest, message_type=Message.QUESTION, is_answered=False)
            context['unanswered_questions'] = qs.count()

        if self.permissions.ask_questions:
            qs = Message.objects.filter(contest=self.contest, message_type=Message.QUESTION, sender=me, messageuser__isnull=True)
            context['unread_answers'] = qs.count()

    def is_allowed(self, permissions):
        return False

    def get_limit_policy(self):
        return ContestAttemptLimitPolicy(self.contest, self.request.user)

    def dispatch(self, request, contest_id, *args, **kwargs):
        self.contest = get_object_or_404(Contest, pk=contest_id)
        self.service = create_contest_service(self.contest)
        self.timing = ContestTiming(self.contest)
        member_flags = ContestMemberFlags.load(self.contest, request.user)
        self.permissions = calculate_contest_permissions(self.contest, member_flags)

        if not self.is_allowed(self.permissions):
            raise PermissionDenied()
        return super(BaseContestView, self).dispatch(request, self.contest, *args, **kwargs)


class ProblemResolverMixin(object):
    def get_context_data(self, **kwargs):
        context = super(ProblemResolverMixin, self).get_context_data(**kwargs)
        context['resolver'] = ProblemResolver(self.contest)
        return context


class GeneralView(BaseContestView):
    def is_allowed(self, permissions):
        return permissions.standings

    def get(self, request, contest):
        return redirect('contests:standings', contest.id)


AUTOREFRESH = 'autorefresh'
FILTER = 'filter'
USERNAMES = 'usernames'


class StandingsView(BaseContestView):
    tab = 'standings'
    wide = False
    raw = False

    def get_template_name(self):
        if self.wide:
            return 'contests/standings_wide.html'
        if self.raw:
            return 'contests/standings_raw.html'

        return 'contests/standings.html'

    def is_allowed(self, permissions):
        return permissions.standings

    def get_context_data(self, **kwargs):
        context = super(StandingsView, self).get_context_data(**kwargs)
        context['no_standings_yet_message'] = self.service.get_no_standings_yet_message()
        return context

    def _parse_autorefresh(self, request):
        autorefresh = request.session.get(AUTOREFRESH, False)

        if AUTOREFRESH in request.GET:
            autorefresh_requested = (request.GET.get(AUTOREFRESH) == '1')
            if autorefresh != autorefresh_requested:
                request.session[AUTOREFRESH] = autorefresh_requested
                return autorefresh_requested

        return autorefresh

    def _parse_filter(self, request, filters):
        fid = request.GET.get(FILTER)
        if fid is not None:
            try:
                fid = int(fid)
            except (ValueError, TypeError):
                pass
            for f in filters:
                if f.id == fid:
                    return (fid, re.compile(f.regex))
        return (None, None)

    def get(self, request, contest):
        autorefresh = self._parse_autorefresh(request)

        filters = contest.userfilter_set.order_by('name')
        cur_filter_id, user_regex = self._parse_filter(request, filters)

        # privileged users may click on contestants to see their solutions
        user_url = None
        if not self.wide and self.permissions.all_solutions:
            user_url = reverse('contests:all_solutions', kwargs={'contest_id': contest.id})

        my_id = request.user.id if request.user.is_authenticated else None
        contest_results = None

        if self.service.are_standings_available(self.permissions, self.timing):
            # Do not show standings before the contest because they contain names of problems!
            frozen = (self.timing.is_freeze_applicable()) and (not self.permissions.always_unfrozen_standings)
            contest_results = self.service.make_contest_results(contest, frozen=frozen, user_regex=user_regex)

        show_usernames = request.GET.get(USERNAMES) == '1'

        context = self.get_context_data(results=contest_results, my_id=my_id, user_url=user_url,
                                        autorefresh=autorefresh, filters=filters, cur_filter_id=cur_filter_id,
                                        show_usernames=show_usernames)

        template_name = self.get_template_name()
        return render(request, template_name, context)


class ContestProblemsetMixin(object):
    template_name_later = 'contests/problems_later.html'

    def is_problemset_available(self):
        if self.timing.get() == ContestTiming.BEFORE:
            return self.permissions.problems_before
        return True

    def later(self, request):
        context = self.get_context_data()
        return render(request, self.template_name_later, context)


class StatementsFileView(ContestProblemsetMixin, BaseContestView):
    tab = 'problems'

    def is_allowed(self, permissions):
        return permissions.problems

    def get(self, request, contest, filename):
        if not self.is_problemset_available():
            return self.later(request)

        return serve_resource_metadata(request, contest.statements, force_download=False)


class ProblemsView(ContestProblemsetMixin, BaseContestView):
    tab = 'problems'
    template_name = 'contests/problems_list.html'

    def is_allowed(self, permissions):
        return permissions.problems

    def get(self, request, contest):
        if not self.is_problemset_available():
            return self.later(request)

        problems = [(make_letter(i), problem) for i, problem in enumerate(contest.get_problems())]
        context = self.get_context_data(statements=contest.statements, problems=problems)
        return render(request, self.template_name, context)


class ProblemView(ProblemStatementMixin, ContestProblemsetMixin, BaseContestView):
    tab = 'problems'
    template_name = 'contests/problem.html'

    def is_allowed(self, permissions):
        return permissions.problems

    def get(self, request, contest, problem_id):
        if not self.is_problemset_available():
            return self.later(request)

        problem = Problem.objects.filter(pk=problem_id, link_to_contest__contest=self.contest).first()
        if problem is None:
            return redirect('contests:problems', contest.id)

        context = self.get_context_data()
        context['problem'] = problem
        context['statement'] = self.make_statement(problem)
        context['problem_to_submit'] = problem.id
        context['letter'] = ProblemResolver(contest).get_letter(problem.id)
        return render(request, self.template_name, context)


class ProblemFileView(ProblemStatementMixin, ContestProblemsetMixin, BaseContestView):
    tab = 'problems'
    template_name = 'contests/problem.html'

    def is_allowed(self, permissions):
        return permissions.problems

project/contests/templates/contests/all_questions.html
{% extends 'contests/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_contests %}
{% load irunner_pagination %}
{% load irunner_users %}

{% block subtitle %}{% trans 'Questions' %}{% endblock %}

{% block main %}
    {% if not object_list %}
        <div class="ir-absence">{% trans 'No questions' %}</div>
    {% else %}
        {% irunner_pagination pagination_context %}
        {% for question in object_list %}
            {% irunner_contests_question question contest_id=contest.id problem_resolver=resolver url_pattern='contests:all_questions_answers' %}
        {% endfor %}
    {% endif %}
{% endblock %}

project/contests/templates/contests/all_solutions.html
{% extends 'contests/base.html' %}

{% load i18n %}
{% load irunner_contests %}
{% load irunner_proglangs %}
{% load irunner_solutions %}
{% load irunner_pagination %}
{% load irunner_users %}
{% load bootstrap3 %}
{% load widget_tweaks %}

{% block subtitle %}{% trans 'All solutions' %}{% endblock %}

{% block main %}
    <form method="get" class="form-inline">
        <div class="ir-solution-filter">
            <div class="pull-right">
                {{ problem_form.problem }}
                {{ user_form.user }}
                {% if filter_form %}
                    {% render_field filter_form.state class='form-control' %}
                {% endif %}
                <button type="submit" class="btn btn-default">
                    {% trans 'Apply' %}
                </button>
            </div>
        </div>
    </form>

    {% if object_list %}
        {% irunner_pagination pagination_context %}
        <form method="post">
        {% csrf_token %}
        <table class="table table-condensed table-striped ir-compact-table">
            <thead>
                <tr>
                    <th><input type="checkbox" id="selectall"></th>
                    <th>{% trans 'Problem' %}</th>
                    <th>{% trans 'Author' %}</th>
                    <th>{% trans 'Time' %}</th>
                    <th>{% trans 'File' %}</th>
                    <th>{% trans 'Status' %}</th>
                    {% if show_scores %}
                        <th>{% trans 'Score' %}</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for solution in object_list %}
                <tr{% if solution.is_disqualified %} class="warning"{% endif %}>
                    <td><input type="checkbox" class="ir-checkbox" name="id" value="{{ solution.id }}" style="margin: 0"></td>
                    <td>
                        <a href="{% url 'contests:problem' contest.id solution.problem_id %}">{% irunner_contests_showproblem resolver solution.problem_id %}</a>
                    </td>
                    <td>{% irunner_users_show solution.author %}</td>
                    <td>{{ solution.reception_time }}</td>
                    <td>
                        {% irunner_proglangs_compilerbox solution.compiler tooltip=True %}
                        <a href="{% url 'solutions:source' solution.id %}" class="ir-monospace">{{ solution.source_code.filename }}</a>
                        <span class="ir-file-size">({{ solution.source_code.size|filesizeformat }})</span>
                    </td>
                    <td>
                        <a href="{% url 'solutions:main' solution.id %}">{% irunner_solutions_judgementbox solution.best_judgement tooltip=True %}</a>
                    </td>
                    {% if show_scores %}
                        <td>{% irunner_solutions_scorebox solution.best_judgement %}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% buttons %}
            <div class="btn-group">
                <button type="submit" name="disqualify" class="btn btn-sm btn-default ir-checkbox-driven">
                    {% bootstrap_icon 'thumbs-down' %} <span class="ir-icon-label">{% trans 'Disqualify' %}</span>
                </button>
                <button type="submit" name="qualify" class="btn btn-sm btn-default ir-checkbox-driven">
                    {% bootstrap_icon 'thumbs-up' %} <span class="ir-icon-label">{% trans 'Cancel the disqualification' %}</span>
                </button>
            </div>
        {% endbuttons %}
        </form>

        <script>
            $(document).ready(irSetUpSelectAll);
        </script>
    {% else %}
        <div class="ir-absence">
            {% trans 'No solutions' %}
        </div>
    {% endif %}
{% endblock %}

project/contests/templates/contests/base.html
{% extends 'base.html' %}

{% block title %}{% block subtitle %}{% endblock %} &mdash; {{ contest }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        {% include 'contests/sidebar.html' %}

        {% block extrasidebar %}
        {% endblock %}
    </div>
    <div class="col-md-9">
        {% block main %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/contests/templates/contests/contest_confirm_delete.html
{% extends "contests/settings_base.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block submain %}
    <h3>{% trans 'Delete the contest' %}</h3>
    <p>{% trans 'Are you sure you want to permanently delete the contest? This action cannot be undone.' %}</p>
    <form action="" method="post">
        {% csrf_token %}
        {% buttons %}
            <input type="submit" class="btn btn-danger" value="{% trans 'Confirm' %}" />
	        <a href="{% url 'contests:settings_properties' contest.id %}" class="btn btn-link">
	            {% trans 'Cancel' %}
	        </a>
        {% endbuttons %}
    </form>
{% endblock %}

project/contests/templates/contests/export.html
{% extends 'contests/base.html' %}

{% load static %}
{% load bootstrap3 %}
{% load i18n %}

{% block subtitle %}{% trans 'Export' %}{% endblock %}

{% block main %}
    <h3>S4RiS Standings Dancing</h3>
    <ul>
        <li><a href="{% url 'contests:export_s4ris' contest.id %}">JSON</a></li>
        <li><a href="{% static 'S4RiS-StanD/index.html' %}">{% trans 'System' %}</a></li>
    </ul>

    <h3>ejudge</h3>
    <ul>
        <li><a href="{% url 'contests:export_ejudge' contest.id %}">XML</a></li>
    </ul>
{% endblock %}

project/contests/templates/contests/messages.html
{% extends 'contests/base.html' %}

{% load irunner_contests %}
{% load irunner_users %}
{% load bootstrap3 %}
{% load i18n %}

{% block subtitle %}{% trans 'Messages' %}{% endblock %}

{% block main %}
    {% if permissions.manage_messages %}
        <div class="form-group text-right">
            <a href="{% url 'contests:messages_new' contest.id %}" class="btn btn-default">
                {% bootstrap_icon 'pencil' %} <span class="ir-icon-label">{% trans 'New message' %}</span>
            </a>
        </div>
    {% endif %}
    {% if not messages %}
        <div class="ir-absence">{% trans 'No messages' %}</div>
    {% else %}
        {% for message in messages %}
            {% irunner_contests_message message edit_mode=permissions.manage_messages contest_id=contest.id %}
        {% endfor %}
    {% endif %}
{% endblock %}

project/contests/templates/contests/messages_form.html
{% extends 'contests/base.html' %}

{% load irunner_users %}
{% load bootstrap3 %}
{% load i18n %}

{% block subtitle %}{% trans 'Messages' %}{% endblock %}

{% block main %}
    <form method="post" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}

        {% buttons layout='horizontal' %}
            <button type="submit" class="btn btn-primary">
                {% if new %}{% trans 'Send' %}{% else %}{% trans 'Save' %}{% endif %}
            </button>
            <a href="{% url 'contests:messages' contest.id %}" class="btn btn-link">
                {% trans 'Cancel' %}
            </a>
        {% endbuttons %}
    </form>
{% endblock %}

project/contests/templates/contests/settings_filter.html
{% extends 'contests/settings_base.html' %}

{% load bootstrap3 %}
{% load i18n %}

{% block submain %}
    <h3>{% trans 'User filters' %}</h3>
    <form method="post" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_formset formset show_label=True layout='horizontal' %}
        {% buttons layout='horizontal' %}
            <button type="submit" class="btn btn-primary">
                {% trans 'Save' %}
            </button>
            <a href="{% url 'contests:settings_users' contest.id %}" class="btn btn-link">
                {% trans 'Back' %}
            </a>
        {% endbuttons %}
    </form>
{% endblock %}

project/contests/templates/contests/settings_users.html
{% extends 'contests/settings_base.html' %}

{% load i18n %}
{% load irunner_users %}
{% load bootstrap3 %}

{% block submain %}
    {% bootstrap_messages %}

    {% for view_model in view_models %}
        {# view_model is RoleUsersViewModel #}
        <div class="pull-right">
            <a href="{% url 'contests:settings_user_role' contest.id view_model.tag %}" class="btn btn-sm btn-default">
                {% bootstrap_icon 'pencil' %} <span class="ir-icon-label">{% trans 'Edit the list' %}</span>
            </a>
            {% if view_model.enable_filters %}
                <a href="{% url 'contests:settings_filters' contest.id %}" class="btn btn-sm btn-default">
                    {% bootstrap_icon 'filter' %} <span class="ir-icon-label">{% trans 'Filters' %}</span>
                </a>
            {% endif %}
        </div>
        <h3>{{ view_model.name_plural }}</h3>
        {% if view_model.users %}
            <ol>
                {% for user in view_model.users %}
                    <li><a href="{% url 'users:profile_show' user.id %}">{% irunner_users_card user %}</a> <span class="ir-username-aux">{{ user.username }}</span></li>
                {% endfor %}
            </ol>
        {% else %}
            <div class="ir-absence">{% trans 'No users are set' %}</div>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% endblock %}

project/contests/templates/contests/standings.html
{% extends 'contests/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_problems %}
{% load irunner_solutions %}
{% load irunner_contests %}

{% block subtitle %}{% trans 'Standings' context 'contest' %}{% endblock %}

{% block extrasidebar %}
    {% include 'contests/standings_extra_controls.html' %}
{% endblock %}

{% block main %}
    {% include 'contests/standings_body.html' %}
{% endblock %}

{% block foot %}
    {% if autorefresh %}
        <script>
            function poll() {
                $.get("{% url 'contests:standings_raw' contest.id %}{% if cur_filter_id != None %}?filter={{ cur_filter_id }}{% endif %}", function(data) {
                    $("#ir_container").html(data);
                    setTimeout(poll, 30000);
                }).fail(function() {
                    setTimeout(poll, 60000);
                });
            }
            $(document).ready(function() {
                poll();
            });
        </script>
    {% endif %}
{% endblock %}