project/api/urls.py
from django.conf.urls import url

from . import views
from contests.globalviews import ContestsApiView

app_name = 'api'

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view()),
    url(r'^fs/(?P<filename>new)$', views.NewFileView.as_view()),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/cancel$', views.JobCancelView.as_view()),
    url(r'^compiler-settings$', views.CompilerSettingsView.as_view()),
    url(r'^plagiarism/take$', views.PlagiarismTakeView.as_view()),
    url(r'^plagiarism/put$', views.PlagiarismPutView.as_view()),
    url(r'^sleep$', views.SleepView.as_view()),
    url(r'^printing$', views.PrintingView.as_view()),
    url(r'^printing/(?P<printout_id>\d+)$', views.PrintingDoneView.as_view()),
    url(r'^auth/check$', views.AuthCheckView.as_view()),
    url(r'^contests$', ContestsApiView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/proglangs/urls.py
from django.conf.urls import url

from . import views

app_name = 'proglangs'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new/$', views.CreateCompilerView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.UpdateCompilerView.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteCompilerView.as_view(), name='delete'),
]

project/proglangs/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from proglangs.langlist import ProgrammingLanguage


class Compiler(models.Model):
    handle = models.CharField(_('string identifier'), max_length=30, unique=True)
    language = models.CharField(_('language'), max_length=8, choices=ProgrammingLanguage.CHOICES, default=ProgrammingLanguage.UNKNOWN, blank=True)
    description = models.CharField(_('description'), max_length=255, blank=True)
    default_for_courses = models.BooleanField(_('compiler is enabled by default in new courses'), default=False)
    default_for_contests = models.BooleanField(_('compiler is enabled by default in new contests'), default=False)

    def __str__(self):
        return self.description

    class Meta:
        ordering = ['description']


class CompilerDetails(models.Model):
    compiler = models.OneToOneField(Compiler, on_delete=models.CASCADE, primary_key=True)
    compile_command = models.CharField(_('compile command'), max_length=1023, blank=True)
    run_command = models.CharField(_('run command'), max_length=1023, blank=True)

project/proglangs/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from common.constants import EMPTY_SELECT

from proglangs.models import Compiler


class DeleteCompilerForm(forms.Form):
    replacement = forms.ModelChoiceField(label=_('Compiler for replacement'), queryset=None, required=True, empty_label=EMPTY_SELECT)

    def __init__(self, *args, **kwargs):
        current_compiler = kwargs.pop('current_compiler', None)
        super().__init__(*args, **kwargs)
        if current_compiler is not None:
            self.fields['replacement'].queryset = Compiler.objects.\
                filter(language=current_compiler.language).\
                exclude(id=current_compiler.id)

project/proglangs/views.py
from __future__ import unicode_literals

from django.db import transaction
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from cauth.mixins import StaffMemberRequiredMixin

from .forms import DeleteCompilerForm
from .models import Compiler
from .usage import replace_compiler


class IndexView(StaffMemberRequiredMixin, generic.ListView):
    template_name = 'proglangs/index.html'
    context_object_name = 'compilers'

    def get_queryset(self):
        return Compiler.objects.all()


class CreateCompilerView(StaffMemberRequiredMixin, generic.CreateView):
    model = Compiler
    template_name = 'proglangs/edit.html'
    fields = ['handle', 'language', 'description', 'default_for_courses', 'default_for_contests']

    def get_success_url(self):
        return reverse('proglangs:index')


class UpdateCompilerView(StaffMemberRequiredMixin, generic.UpdateView):
    model = Compiler
    template_name = 'proglangs/edit.html'
    fields = ['handle', 'language', 'description', 'default_for_courses', 'default_for_contests']

    def get_success_url(self):
        return reverse('proglangs:index')


class DeleteCompilerView(StaffMemberRequiredMixin, generic.detail.TemplateResponseMixin, generic.detail.ContextMixin, generic.View):
    template_name = 'proglangs/delete.html'

    def get(self, request, pk):
        compiler = get_object_or_404(Compiler, pk=pk)
        form = DeleteCompilerForm(current_compiler=compiler)
        context = self.get_context_data(object=compiler, form=form)
        return self.render_to_response(context)

    def post(self, request, pk):
        compiler = get_object_or_404(Compiler, pk=pk)
        form = DeleteCompilerForm(request.POST, current_compiler=compiler)
        if form.is_valid():
            with transaction.atomic():
                replace_compiler(compiler.id, form.cleaned_data['replacement'].id)
                compiler.delete()
            return redirect('proglangs:index')
        context = self.get_context_data(object=compiler, form=form)
        return self.render_to_response(context)

project/proglangs/templates/proglangs/create.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_proglangs %}

{% block title %}{% trans 'New compiler' %}{% endblock %}

{% block content %}

<form method="post" class="form">
    {% csrf_token %}

    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans 'Create' %}</button>
        <a href="{% url 'proglangs:index' %}" class="btn btn-link">{% trans 'Cancel' %}</a>
    {% endbuttons %}
</form>

{% endblock %}

project/proglangs/templates/proglangs/delete.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_proglangs %}

{% block title %}{% trans 'Delete' %} {{ object.handle }}{% endblock %}

{% block content %}

<form method="post" class="form">
    {% csrf_token %}

    <p>{% blocktrans with id=object.handle %}The compiler {{ id }} is going to be deleted. Choose a compiler that will be used instead.{% endblocktrans %}</p>

    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
        <a href="{% url 'proglangs:update' object.id %}" class="btn btn-link">{% trans 'Cancel' %}</a>
    {% endbuttons %}
</form>

{% endblock %}

project/proglangs/templates/proglangs/edit.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_proglangs %}

{% block title %}{% trans 'Compiler' %} {{ object.handle }} ({{ object.description }}){% endblock %}

{% block content %}

<form method="post" class="form">
    {% csrf_token %}

    {% if object %}
        {% irunner_proglangs_commandlines object expanded=True %}
    {% endif %}

    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
        {% if object %}<a href="{% url 'proglangs:delete' object.id %}" class="btn btn-default">{% trans 'Delete' %}</a>{% endif %}
        <a href="{% url 'proglangs:index' %}" class="btn btn-link">{% trans 'Cancel' %}</a>
    {% endbuttons %}
</form>

{% endblock %}

project/proglangs/templates/proglangs/index.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_proglangs %}
{% load irunner_yesno %}

{% block content %}

<h1>{% block title %}{% trans 'Compilers' %}{% endblock %}</h1>

<div class="form-group">
    <a href="{% url 'proglangs:create' %}" class="btn btn-default">{% bootstrap_icon 'plus' %} <span class="ir-icon-label">{% trans 'New compiler' %}</span></a> 
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>{% trans 'String identifier' %}</th>
            <th>{% trans 'Description' %}</th>
            <th>{% trans 'Language' %}</th>
            <th>{% trans 'For courses?' %}</th>
            <th>{% trans 'For contests?' %}</th>
        </tr>
    </thead>
    <tbody>
    {% for compiler in compilers %}
        <tr>
            <td class="ir-monospace"><a href="{% url 'proglangs:update' compiler.id %}">{{ compiler.handle }}</a></td>
            <td>{{ compiler.description }}</td>
            <td>{% irunner_proglangs_compilerbox compiler tooltip=False %}</td>
            <td>{% irunner_yesno compiler.default_for_courses %}</td>
            <td>{% irunner_yesno compiler.default_for_contests %}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

project/proglangs/templates/proglangs/irunner_proglangs_commandlines_tag.html
{% load i18n %}

{% load irunner_proglangs %}

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    {% for compiler in compilers %}
        <div class="panel panel-default">
            <div class="panel-heading" role="tab">
                <span class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#ir_block_{{ forloop.counter }}" aria-expanded="{% if expanded %}true{% else %}false{% endif %}" aria-controls="ir_block_{{ forloop.counter }}">
                        {{ compiler.description }}
                    </a>
                </span>
            </div>
            <div id="ir_block_{{ forloop.counter }}" class="panel-collapse collapse{% if expanded %} in{% endif %}" role="tabpanel">
                <div class="panel-body">
                    {% if compiler.compilerdetails %}
                        <dl>
                            <dt>{% trans 'Language' %}</dt>
                            <dd>{% irunner_proglangs_compilerbox compiler tooltip=False %}</dd>

                            <dt>{% trans 'Compile command line' %}</dt>
                            <dd><samp class="small">{{ compiler.compilerdetails.compile_command }}</samp></dd>

                            <dt>{% trans 'Run command line' %}</dt>
                            <dd><samp class="small">{{ compiler.compilerdetails.run_command }}</samp></dd>
                        </dl>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

project/proglangs/templates/proglangs/irunner_proglangs_compilerbox_tag.html
<div class="ir-box ir-langbox ir-langbox-{{ compiler.language }}"{% if tooltip %} title="{{ compiler.description }}"{% endif %}><span>{{ compiler.get_language_display }}</span></div>

project/proglangs/templates/proglangs/irunner_proglangs_langbox_tag.html
<div class="ir-box ir-langbox ir-langbox-{{ compiler.language }}"{% if tooltip %} title="{{ compiler.description }}"{% endif %}><span>{{ compiler.get_language_display }}</span></div>